# Generated by Django 3.0.6 on 2020-06-16 01:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 16, 1, 6, 50, 730212, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 1, 6, 50, 732208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 1, 6, 50, 731211, tzinfo=utc)),
        ),
    ]
