# Generated by Django 3.0.6 on 2020-06-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200615_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='joined_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(),
        ),
    ]
