# Generated by Django 3.0.6 on 2020-06-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200615_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(default='', help_text='Bio information for this author.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Add tags for the post.', to='blog.Tag'),
        ),
    ]
